# Generated by Django 3.1.1 on 2020-09-06 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('betapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinnerMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.CharField(max_length=200)),
                ('player2', models.CharField(max_length=200)),
                ('player1odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('player2odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('canBet', models.BooleanField(default=True)),
                ('winner', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WinnerBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('winner', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betapp.winnermatch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
