# Generated by Django 3.1.1 on 2020-09-06 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betapp', '0002_winnerbet_winnermatch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='points',
            options={'verbose_name_plural': 'Points'},
        ),
        migrations.AlterModelOptions(
            name='winnermatch',
            options={'verbose_name_plural': 'Winner Matches'},
        ),
    ]
