# Generated by Django 3.1.1 on 2020-09-07 12:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betapp', '0004_winnerbet_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='winnermatch',
            name='player1winchance',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
