# Generated by Django 3.1.1 on 2020-09-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betapp', '0005_winnermatch_player1winchance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winnermatch',
            name='player1winchance',
            field=models.IntegerField(default=50),
        ),
    ]
