# Generated by Django 3.1.1 on 2020-09-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betapp', '0006_auto_20200907_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winnermatch',
            name='player1odds',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='winnermatch',
            name='player1winchance',
            field=models.IntegerField(default=50, verbose_name='Player 1 win chance (%)'),
        ),
        migrations.AlterField(
            model_name='winnermatch',
            name='player2odds',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5),
        ),
    ]
