# Generated by Django 3.1.1 on 2020-09-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betapp', '0008_winnermatch_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='winnerbet',
            name='payout',
            field=models.IntegerField(default=0),
        ),
    ]
