# Generated by Django 3.1.1 on 2020-09-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betapp', '0010_points_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='winnermatch',
            name='bestof',
            field=models.IntegerField(choices=[(3, 'Bo3'), (5, 'Bo5'), (7, 'Bo7')], default=3),
        ),
        migrations.AddField(
            model_name='winnermatch',
            name='resL0',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5),
        ),
        migrations.AddField(
            model_name='winnermatch',
            name='resL1',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5),
        ),
        migrations.AddField(
            model_name='winnermatch',
            name='resL2',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5),
        ),
        migrations.AddField(
            model_name='winnermatch',
            name='resL3',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5),
        ),
        migrations.AddField(
            model_name='winnermatch',
            name='resW0',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5),
        ),
        migrations.AddField(
            model_name='winnermatch',
            name='resW1',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5),
        ),
        migrations.AddField(
            model_name='winnermatch',
            name='resW2',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5),
        ),
        migrations.AddField(
            model_name='winnermatch',
            name='resW3',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='winnermatch',
            name='winner',
            field=models.IntegerField(choices=[(0, 'No winner'), (1, 'Player 1'), (2, 'Player2')], default=0),
        ),
    ]
