# Generated by Django 3.1.1 on 2020-09-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betapp', '0011_auto_20200916_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='winnerbet',
            name='resultBet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='winnermatch',
            name='p1maps',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], default=0, verbose_name='Map wins: Player 1'),
        ),
        migrations.AddField(
            model_name='winnermatch',
            name='p2maps',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], default=0, verbose_name='Map wins: Player 2'),
        ),
    ]
