# Generated by Django 3.1.1 on 2020-09-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betapp', '0012_auto_20200916_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='winnerbet',
            name='result',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='winnerbet',
            name='won',
            field=models.BooleanField(default=False),
        ),
    ]
