# Generated by Django 3.1.1 on 2021-02-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betapp', '0016_auto_20201102_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='resets',
            field=models.IntegerField(default=0),
        ),
    ]
