# Generated by Django 3.1.1 on 2021-04-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betapp', '0017_points_resets'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Question (e.g. Is next game cannon rush)')),
                ('player1', models.CharField(max_length=200, verbose_name='Result 1 (e.g. Yes)')),
                ('player2', models.CharField(max_length=200, verbose_name='Result 2 (e.g. No)')),
                ('player1winchance', models.IntegerField(default=50, verbose_name='Result 1 probability (%)')),
                ('player2winchance', models.IntegerField(default=50, verbose_name='Result 2 probability (%)')),
                ('player1odds', models.DecimalField(decimal_places=2, default=2, max_digits=11)),
                ('player2odds', models.DecimalField(decimal_places=2, default=2, max_digits=11)),
            ],
        ),
    ]
