# Generated by Django 3.1.1 on 2021-04-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betapp', '0018_custommatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='custommatch',
            name='canBet',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='custommatch',
            name='winner',
            field=models.IntegerField(choices=[(0, 'No winner'), (1, 'Result 1'), (2, 'Result 2')], default=0),
        ),
    ]
