# Generated by Django 3.1.1 on 2021-04-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betapp', '0020_custombet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommatch',
            name='winner',
            field=models.IntegerField(choices=[(0, 'No result'), (1, 'Result 1'), (2, 'Result 2')], default=0),
        ),
    ]
