# Generated by Django 3.1.1 on 2021-04-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betapp', '0022_miscdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miscdata',
            name='data',
            field=models.TextField(default=''),
        ),
    ]
